erpAPP/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("account-type/",views.AccountType.as_view(),name="account_type"),
    # path("complete-transaction/",views.CompleteTransaction,name="transaction_complete"),
    path("transferMoney/",views.transferMoney.as_view(), name='transferMoney'),
    path("transferMoney/success/",views.transferMoneysuccess, name='transferMoneysuccess'),
    path("financialAccount/",views.financialAccount, name='financialAccount'),
    path("financialAccount/accept/<int:pk>/",views.accept, name='accept'),
    path("financialAccount/decline/<int:pk>/",views.decline, name='decline'),
    path("add-project/",views.addproject.as_view(), name='addproject'),
    path("add-project-print/",views.ProjectSuccessPDFView.as_view(), name='addprojectpdf'),
    path("ptc-project/",views.ptcproject, name='ptc_project'),
    path("check-statement/",views.CheckStatement, name='check-statement'),
    path("check-statement/categorize/<str:txnID>/",views.Categorize, name='categorize'),
    path("check-statement/categorize/<str:txnID>/<int:pk>/",views.CategorizeExpense, name='categorize'),
    path("view-statement/",views.ViewStatement, name='view-statement'),
    path("view-statement/<int:id>/mark-audit/",views.ViewMarkAudit, name='mark-audit-statement'),
    path("view-statement/<int:id>/mark-account/",views.ViewMarkAccount, name='view-mark-statement'),
    path("view-statement/<int:ptcID>/expense-list/",views.ExpenseList, name='expense-list'),
    path("view-statement/mark-account/<str:txnID>/",views.MarkAccount, name='mark-account'),
    path("view-project/",views.ViewProject, name='view-project'),
]

flexmotivTechnologies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import  static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('', include('django.contrib.auth.urls')),
    path('access/', views.access,name="access"),
    path("erp/",include("erpAPP.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

erpAPP/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class fm_user_extend(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    uopeningBalance = models.FloatField(default=0)
    uBalance = models.FloatField(default=0)
    uUnconfirmed = models.FloatField(default=0)
    uDeclined = models.FloatField(default=0)

class fm_txn(models.Model):
    txnID = models.CharField(max_length=20,primary_key=True)
    accID = models.IntegerField(default=0)
    txnDate = models.DateField(auto_now=False,auto_now_add=False,null=False,blank=False)
    txnPostedDate = models.DateField(auto_now=False,auto_now_add=False,null=False,blank=False)
    txnCheque = models.FloatField()
    txnDir = models.CharField(max_length=2)
    txnDesc = models.CharField(max_length=100)
    txnValue = models.FloatField()
    txnBalance = models.FloatField()
    txnAuditFile = models.URLField(max_length=200)
    txnType = models.CharField(max_length=1,default='U')
    txnAccounted = models.BooleanField(default=0)
    txnAudited = models.BooleanField(default=0)
    prID = models.IntegerField(null=True)
    ptcID = models.IntegerField(null=True)
    bhlID = models.IntegerField(null=True)
    transc_time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.txnID

# class CSVfileStorage(models.Model):
#     txnAuditFileStorage = models.FileField(upload_to="file_link",max_length=100,unique=True)


class fm_utrans(models.Model):
    utranDate = models.DateField(auto_now_add=True)
    txnID = models.CharField(max_length=20,null=True)
    utranDesc = models.CharField(max_length=50,verbose_name='Description')
    utranValue = models.FloatField(verbose_name='Amount',null=True)
    utranConfirmed = models.CharField(max_length=1,default='N')
    utranSender = models.CharField(max_length=10,default='no')
    utranReceiver = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='Receiver')
    def get_absolute_url(self):
        return reverse('transferMoney')

class fm_project(models.Model):
    prTitle = models.CharField(max_length=50,verbose_name='Project Title')
    prDesc = models.CharField(max_length=200,verbose_name = 'Project Description')
    prManagers_1 = models.ForeignKey(User,on_delete=models.CASCADE,related_name='first_project_manager',verbose_name ='Project Manager 1')
    prManagers_2 = models.ForeignKey(User,blank=True,null=True,on_delete=models.SET_NULL,related_name='second_project_manager',verbose_name ='Project Manager 2')
    prManagers_3 = models.ForeignKey(User,blank=True,null=True,on_delete=models.SET_NULL,related_name='third_project_manager',verbose_name ='Project Manager 3')
    prManagers_4 = models.ForeignKey(User,blank=True,null=True,on_delete=models.SET_NULL,related_name='fourth_project_manager',verbose_name ='Project Manager 4')
    prManagers_5 = models.ForeignKey(User,blank=True,null=True,on_delete=models.SET_NULL,related_name='fifth_project_manager',verbose_name ='Project Manager 5')
    prManagers_6 = models.ForeignKey(User,blank=True,null=True,on_delete=models.SET_NULL,related_name='sixth_project_manager',verbose_name ='Project Manager 6')
    prBudget = models.FloatField(default=0,verbose_name='Total Budget')
    prBalance = models.FloatField(default=0,verbose_name='Balance of budget')
    def __str__(self):
        return self.prTitle
class fm_budgethead(models.Model):
    prID = models.ForeignKey(fm_project,on_delete = models.CASCADE)
    bhTitle = models.CharField(max_length=50)
    bhLimit = models.FloatField(default=0)
    bhBalance = models.FloatField(default=0)
    bhBalanceDate = models.DateField(auto_now=True)
    def __str__(self):
        return self.bhTitle


class fm_ptcform(models.Model):
    uID = models.ForeignKey(User,on_delete=models.CASCADE)
    ptcValue = models.FloatField(default=0)
    ptcType = models.CharField(max_length=40,null=True)
    prID = models.ForeignKey(fm_project,on_delete=models.CASCADE)
    ptcDate = models.DateField(auto_now=True)
    ptcApproved = models.BooleanField(default=0)
    ptcApprovedBy = models.CharField(max_length=50,null=True)
    txnID = models.ForeignKey(fm_txn,null=True,on_delete=models.SET_NULL)
    ptcType_D_E = models.CharField(max_length=1,null=True)
    class Meta:
        get_latest_by = 'uID'

class fm_ptctrans(models.Model):
    ptctransDate = models.DateField(auto_now=False,auto_now_add=False)
    ptcID = models.ForeignKey(fm_ptcform,on_delete=models.CASCADE)
    ptctransValue = models.FloatField()
    ptctransInvoiceStatus = models.CharField(max_length=1)
    ptctransInvoiceFile = models.FileField(upload_to="InvoiceFile",max_length=100,unique=True)
    ptctransHead = models.ForeignKey(fm_budgethead,on_delete=models.CASCADE)
    prID = models.ForeignKey(fm_project,on_delete=models.CASCADE)
    uID = models.ForeignKey(User,on_delete=models.CASCADE)
    ptctransApproved = models.BooleanField(default=0)
    ptctransApprovedBy = models.CharField(max_length=50,null=True)
    ptcVendor = models.CharField(max_length=50)
    ptcDesc = models.CharField(max_length=200)
    ptcAccounted = models.BooleanField(default=0)
    ptcAudited = models.BooleanField(default=0)

erpAPP/forms.py
from django import forms
from django.forms import ModelForm
from .models import fm_utrans,fm_project,fm_budgethead,fm_ptcform,fm_ptctrans
from django.contrib.auth.models import User
import datetime
class AccountTypeForm(forms.Form):
    c  = [("1","Main"),("2","BIRAC")]
    choices = forms.ChoiceField(choices=c, label="Select Account Type")

class TransferMoneyForm(forms.ModelForm):
    class Meta:
        model = fm_utrans
        exclude = ('utranID','txnID','utranConfirmed','utranSender')
    def save(self,user):
        obj = super().save(commit = False)
        obj.utranSender = user
        obj.save()
        return obj

class AddProjectForm(forms.ModelForm):
    class Meta:
        model = fm_project
        exclude = ('prBudget','prBalance')

    def __init__(self, *args,**kwargs):
        super (AddProjectForm,self ).__init__(*args,**kwargs)
        self.fields['prManagers_1'].queryset = User.objects.filter(groups__name='projectmanager')
        self.fields['prManagers_2'].queryset = User.objects.filter(groups__name='projectmanager')
        self.fields['prManagers_3'].queryset = User.objects.filter(groups__name='projectmanager')
        self.fields['prManagers_4'].queryset = User.objects.filter(groups__name='projectmanager')
        self.fields['prManagers_5'].queryset = User.objects.filter(groups__name='projectmanager')
        self.fields['prManagers_6'].queryset = User.objects.filter(groups__name='projectmanager')

class ProjectBudgetForm(forms.Form):
    title = forms.CharField(max_length=50)
    Limit = forms.IntegerField()
    Balance = forms.IntegerField()
class ProjectBudgetForm2(forms.Form):
    title2 = forms.CharField(max_length=50,required=False)
    Limit2 = forms.IntegerField(required=False)
    Balance2 = forms.IntegerField(required=False)
class ProjectBudgetForm3(forms.Form):
    title3 = forms.CharField(max_length=50,required=False)
    Limit3 = forms.IntegerField(required=False)
    Balance3 = forms.IntegerField(required=False)
class ProjectBudgetForm4(forms.Form):
    title4 = forms.CharField(max_length=50,required=False)
    Limit4 = forms.IntegerField(required=False)
    Balance4 = forms.IntegerField(required=False)
class ProjectBudgetForm5(forms.Form):
    title5 = forms.CharField(max_length=50,required=False)
    Limit5 = forms.IntegerField(required=False)
    Balance5 = forms.IntegerField(required=False)
class ProjectBudgetForm6(forms.Form):
    title6 = forms.CharField(max_length=50,required=False)
    Limit6 = forms.IntegerField(required=False)
    Balance6 = forms.IntegerField(required=False)
class ProjectBudgetForm7(forms.Form):
    title7 = forms.CharField(max_length=50,required=False)
    Limit7 = forms.IntegerField(required=False)
    Balance7 = forms.IntegerField(required=False)
class ProjectBudgetForm8(forms.Form):
    title8 = forms.CharField(max_length=50,required=False)
    Limit8 = forms.IntegerField(required=False)
    Balance8 = forms.IntegerField(required=False)
class ProjectBudgetForm9(forms.Form):
    title9 = forms.CharField(max_length=50,required=False)
    Limit9 = forms.IntegerField(required=False)
    Balance9 = forms.IntegerField(required=False)
class ProjectBudgetForm10(forms.Form):
    title10 = forms.CharField(max_length=50,required=False)
    Limit10 = forms.IntegerField(required=False)
    Balance10 = forms.IntegerField(required=False)

class ptcprojectform(forms.Form):
    prID = forms.ModelChoiceField(queryset=fm_project.objects.all(),label="Select project")
class ptctransform(forms.Form):
    Date_ptcform = forms.DateField(label="Date in (YYYY-MM-DD)")
    Vendor = forms.CharField(max_length=50,label="Vendor")
    Description = forms.CharField(max_length=200,label="Desc")
    Value = forms.IntegerField(label="Value")
    Budgets = forms.ModelChoiceField(queryset=fm_budgethead.objects.all(),label="Budgets")
    c  = [("Y","Invoice Available"),("P","Invoice Pending"),("N","Invoice Not Available")]
    choices = forms.ChoiceField(choices=c, label="Invoice Status")
    # InvoiceFile = forms.FileField(label="Upload Invoice")
    def __init__(self,budget_queryset,*args,**kwargs):
        super(ptctransform, self).__init__(*args,**kwargs)
        self.fields["Budgets"].queryset = budget_queryset
    ##Is there any particular file format for Invoice

class ptctransform2(forms.Form):
    Date_ptcform2 = forms.DateField(label="Date in (YYYY-MM-DD)",required=False)
    Vendor2 = forms.CharField(max_length=50,required=False,label="Vendor")
    Description2 = forms.CharField(max_length=200,required=False,label="Desc")
    Value2 = forms.IntegerField(required=False,label="Value")
    Budgets2 = forms.ModelChoiceField(queryset=fm_budgethead.objects.all(),required=False,label="Budgets")
    c  = [("Y","Invoice Available"),("P","Invoice Pending"),("N","Invoice Not Available")]
    choices2 = forms.ChoiceField(choices=c, label="Invoice Status",required=False)
    # InvoiceFile = forms.FileField(label="Upload Invoice")
    def __init__(self,budget_queryset,*args,**kwargs):
        super(ptctransform2, self).__init__(*args,**kwargs)
        self.fields["Budgets2"].queryset = budget_queryset
class ptctransform3(forms.Form):
    Date_ptcform3 = forms.DateField(label="Date in (YYYY-MM-DD)",required=False)
    Vendor3 = forms.CharField(max_length=50,required=False,label="Vendor")
    Description3 = forms.CharField(max_length=200,required=False,label="Desc")
    Value3 = forms.IntegerField(required=False,label="Value")
    Budgets3 = forms.ModelChoiceField(queryset=fm_budgethead.objects.all(),required=False,label="Budgets")
    c  = [("Y","Invoice Available"),("P","Invoice Pending"),("N","Invoice Not Available")]
    choices3 = forms.ChoiceField(choices=c, label="Invoice Status",required=False)
    # InvoiceFile = forms.FileField(label="Upload Invoice")
    def __init__(self,budget_queryset,*args,**kwargs):
        super(ptctransform3, self).__init__(*args,**kwargs)
        self.fields["Budgets3"].queryset = budget_queryset
class ptctransform4(forms.Form):
    Date_ptcform4 = forms.DateField(label="Date in (YYYY-MM-DD)",required=False)
    Vendor4 = forms.CharField(max_length=50,required=False,label="Vendor")
    Description4 = forms.CharField(max_length=200,required=False,label="Desc")
    Value4 = forms.IntegerField(required=False,label="Value")
    Budgets4 = forms.ModelChoiceField(queryset=fm_budgethead.objects.all(),required=False,label="Budgets")
    c  = [("Y","Invoice Available"),("P","Invoice Pending"),("N","Invoice Not Available")]
    choices4 = forms.ChoiceField(choices=c, label="Invoice Status",required=False)
    # InvoiceFile = forms.FileField(label="Upload Invoice")
    def __init__(self,budget_queryset,*args,**kwargs):
        super(ptctransform4, self).__init__(*args,**kwargs)
        self.fields["Budgets4"].queryset = budget_queryset
class ptctransform5(forms.Form):
    Date_ptcform5 = forms.DateField(label="Date in (YYYY-MM-DD)",required=False)
    Vendor5 = forms.CharField(max_length=50,required=False,label="Vendor")
    Description5 = forms.CharField(max_length=200,required=False,label="Desc")
    Value5 = forms.IntegerField(required=False,label="Value")
    Budgets5 = forms.ModelChoiceField(queryset=fm_budgethead.objects.all(),required=False,label="Budgets")
    c  = [("Y","Invoice Available"),("P","Invoice Pending"),("N","Invoice Not Available")]
    choices5 = forms.ChoiceField(choices=c, label="Invoice Status",required=False)
    # InvoiceFile = forms.FileField(label="Upload Invoice")
    def __init__(self,budget_queryset,*args,**kwargs):
        super(ptctransform5, self).__init__(*args,**kwargs)
        self.fields["Budgets5"].queryset = budget_queryset
class ptctransform6(forms.Form):
    Date_ptcform6 = forms.DateField(label="Date in (YYYY-MM-DD)",required=False)
    Vendor6 = forms.CharField(max_length=50,required=False,label="Vendor")
    Description6 = forms.CharField(max_length=200,required=False,label="Desc")
    Value6 = forms.IntegerField(required=False,label="Value")
    Budgets6 = forms.ModelChoiceField(queryset=fm_budgethead.objects.all(),required=False,label="Budgets")
    c  = [("Y","Invoice Available"),("P","Invoice Pending"),("N","Invoice Not Available")]
    choices6 = forms.ChoiceField(choices=c, label="Invoice Status",required=False)
    # InvoiceFile = forms.FileField(label="Upload Invoice")
    def __init__(self,budget_queryset,*args,**kwargs):
        super(ptctransform6, self).__init__(*args,**kwargs)
        self.fields["Budgets6"].queryset = budget_queryset
class ptctransform7(forms.Form):
    Date_ptcform7 = forms.DateField(label="Date in (YYYY-MM-DD)",required=False)
    Vendor7 = forms.CharField(max_length=50,required=False,label="Vendor")
    Description7 = forms.CharField(max_length=200,required=False,label="Desc")
    Value7 = forms.IntegerField(required=False,label="Value")
    Budgets7 = forms.ModelChoiceField(queryset=fm_budgethead.objects.all(),required=False,label="Budgets")
    c  = [("Y","Invoice Available"),("P","Invoice Pending"),("N","Invoice Not Available")]
    choices7 = forms.ChoiceField(choices=c, label="Invoice Status",required=False)
    # InvoiceFile = forms.FileField(label="Upload Invoice")
    def __init__(self,budget_queryset,*args,**kwargs):
        super(ptctransform7, self).__init__(*args,**kwargs)
        self.fields["Budgets7"].queryset = budget_queryset
class ptctransform8(forms.Form):
    Date_ptcform8 = forms.DateField(label="Date in (YYYY-MM-DD)",required=False)
    Vendor8 = forms.CharField(max_length=50,required=False,label="Vendor")
    Description8 = forms.CharField(max_length=200,required=False,label="Desc")
    Value8 = forms.IntegerField(required=False,label="Value")
    Budgets8 = forms.ModelChoiceField(queryset=fm_budgethead.objects.all(),required=False,label="Budgets")
    c  = [("Y","Invoice Available"),("P","Invoice Pending"),("N","Invoice Not Available")]
    choices8 = forms.ChoiceField(choices=c, label="Invoice Status",required=False)

templates/ExpenseList.html
{% extends 'template_base.html' %}
{% block content %}
{% if user_access == 'No' %}
<h2>You cannot access this feature</h2>
{% else %}
<h2> Expense form List (Petty Cash Form)</h2>
{% if error %}
<script>
alert("{{ error }}");
</script>
{% endif %}
{% if obj %}
<table border=1>
  <tr>
    <th>Date</th>
    <th>Vendor</th>
    <th>Value</th>
    <th>Accounted</th>
    <th>Audited</th>
    <th>Invoice</th>
  </tr>
  {% for i in obj %}
  <tr>
    <td>{{ i.ptctransDate }}</td>
    <td>{{ i.ptcVendor }}</td>
    <td>{{ i.ptctransValue }}</td>
    {% if i.ptcAccounted == 1 %}
    <td>Yes</td>
    {% else %}
    <td> <a href="{% url 'view-mark-statement' i.id %}">Mark Accounted</a> </td>
    {% endif %}
    {% if i.ptcAudited == 1 %}
    <td>Yes</td>
    {% else %}
    <td> <a href="{% url 'mark-audit-statement' i.id %}">Mark Audited</a> </td>
    {% endif %}
    {% if i.ptctransInvoiceStatus == "Y" %}
    <td> <a href="/media/{{ i.ptctransInvoiceFile }}/">Invoice Link</a></td>
    {% endif %}
  </tr>
  {% endfor %}
</table>
{% endif %}
{% endif %}
{% endblock %}

templates/MarkAccount.html
{% extends 'template_base.html' %}
{% block content %}
{% block extra_head %}
<style>
  label{
    font-size:20px;
  }
</style>
{% endblock %}
<h1 style="text-align:center;font-size:50px;border:1px solid black;"><b>View Statement(Accountant)</b></h1>
{% if user_access == 'No' %}
<h2>You cannot access this feature</h2>
{% else %}
{% if error %}
<script>
  alert("{{ error }}");
</script>
{% endif %}
{% if form %}
<form method="POST">
  <br>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="markaccountform" value="Submit" style="background:#343a40;border-radius:10px;color:white;width:200px;"">
</form>
{% endif %}
{% if success %}
<h2>{{ success }}</h2>
{% endif %}
{% endif %}
{% endblock %}

templates/account_type.html
{% extends 'template_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% block extra_head %}
<style>
#id_choices{
  width:200px;
}
label{
  font-size:20px;
}
</style>
{% endblock %}
<h1 style="text-align:center;font-size:50px;border:1px solid black;"><b>Upload Statement</b></h1><br>
{% if user_access == 'No' %}
<h2>You cannot access this feature</h2>
{% else %}
<form method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <br>
  <button type="submit" style="background:#343a40;border-radius:10px;color:white;width:100px;">Submit</button>
</form>


<br>
{% if show_csv == "Yes" %}

{% if obj == 0 %}
  <h2>No previous record present corresponding to this account type</h2>
{% else %}
  <table class="table table-striped table-bordered">
    <tr>
    <th>Trans ID</th>
    <th>Trans Date</th>
    <th>Desc</th>
    <th>Trans Value</th>
    <th>Balance</th>
  </tr>
  {% for i in obj %}
    <tr>
    <td>{{i.txnID}}</td>
    <td>{{i.txnDate}}</td>
    <td>{{i.txnDesc}}</td>
    <td>{{i.txnValue}}</td>
    <td>{{i.txnBalance}}</td>
    </tr>
  {% endfor %}
  </table>
{% endif %}


<br>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label>Upload a file</label>
    <br>
    <input type="file" name="file" onclick="myFunction()" style="color:white;background:#343a40;">
    <p>Only accepts CSV files</p>
    <button type="submit" style="background:#343a40;border-radius:10px;color:white;width:100px;">Upload</button>
    <!-- {{form}} -->
  </form>
{% endif %}

<!-- <p id="demo"></p>

<script>
function myFunction() {
  var x = document.getElementById("myFile").value;
  console.log(x);
}
</script -->
{% endif %}
{% endblock %}

templates/add_project_success_pdf.html
<p>Title: {{obj.prTitle}}</p>
<p>Desc: {{obj.prDesc}}</p>
<br>
<table border="1">
  <tr>
    <th> Budget Head </th>
    <th> Budget Amount </th>
    <th> Budget Balance </th>
  </tr>
  {% for i in budget %}
  <tr>
    <td> {{ i.bhTitle }} </td>
    <td> {{ i.bhLimit }} </td>
    <td> {{ i.bhBalance }} </td>
  </tr>
  {% endfor %}
</table>

templates/categorizeExpense.html
{% extends 'template_base.html' %}
{% block content %}
<h1 style="text-align:center;font-size:50px;border:1px solid black;"><b>Check Statement</b></h1>
{% if user_access == 'No' %}
<h2>You cannot access this feature</h2>
{% else %}
{% if e %}
<script>
  alert("{{ e }}");
</script>
{% else %}
<br>
<h1>Expense is successfully updated as category!!</h1>
{% endif %}
{% endif %}
{% endblock %}

templates/decline.html
{% extends 'template_base.html' %}
{% block content %}
<h1 style="text-align:center;font-size:50px;border:1px solid black;"><b>Financial Accounts</b></h1>
<h1>Declined</h1>
{% endblock %}

templates/index.html
{% extends 'template_base.html' %}
{% block content %}

{% if authenticated == 'Yes' %}
    <p>Welcome {{ username }}!!!</p>


{% endif %}
{% endblock %}

templates/ptcproject.html
{% extends 'template_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% block extra_head %}
<style>
 .control-label{
   font-size:20px;
 }
 #id_prID{
   width:200px;
 }
 #id_choices_ptc_e_or_d{
   width:200px;
 }
 </style>
{% endblock %}
<h1 style="text-align:center;font-size:50px;border:1px solid black;"><b>Petty Cash Form</b></h1>
{% if user_access == 'No' %}
<h1>You cannot access this feature</h1>
{% else %}
{% if e %}
<script>
  alert("{{e}}");
</script>
{% endif %}
{% if form%}
<form action="" method="POST" >
  <br>
  {% csrf_token %}
  {{form|crispy}}
  <br>
  <input type="submit" name="ptcprojectform" value="Submit" style="background:#343a40;border-radius:10px;color:white;width:100px;">
</form>
{% endif %}
{% if form_trans %}
<div style="width:100%;">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <br>
  {{ ptc_D_OR_E|crispy }}
  <br>
  <hr>
  1. {{ form_trans.as_table }}
  <input type="file" name="file" style="padding-left:15px;">
  <hr>
  2. {{ form_trans2.as_table }}
  <input type="file" name="file2" style="padding-left:15px;"><hr>
  3. {{ form_trans3.as_table }}
  <input type="file" name="file3" style="padding-left:15px;"><hr>
  4. {{ form_trans4.as_table }}
  <input type="file" name="file4" style="padding-left:15px;"><hr>
  5. {{ form_trans5.as_table }}
  <input type="file" name="file5" style="padding-left:15px;"><hr>
  6. {{ form_trans6.as_table }}
  <input type="file" name="file6" style="padding-left:15px;"><hr>
  7. {{ form_trans7.as_table }}
  <input type="file" name="file7" style="padding-left:15px;"><hr>
  8. {{ form_trans8.as_table }}
  <input type="file" name="file8" style="padding-left:15px;"><hr>
  9. {{ form_trans9.as_table }}
  <input type="file" name="file9" style="padding-left:15px;"><hr>
  10. {{ form_trans10.as_table }}
  <input type="file" name="file10" style="padding-left:25px;"><hr>
  11. {{ form_trans11.as_table }}
  <input type="file" name="file11" style="padding-left:25px;"><hr>
  12. {{ form_trans12.as_table }}
  <input type="file" name="file12" style="padding-left:25px;"><hr>
  13. {{ form_trans13.as_table }}
  <input type="file" name="file13" style="padding-left:25px;"><hr>
  14. {{ form_trans14.as_table }}
  <input type="file" name="file14" style="padding-left:25px;"><hr>
  15. {{ form_trans15.as_table }}
  <input type="file" name="file15" style="padding-left:25px;"><hr>

  <br><input type="submit" name="ptctransform" value="Submit" style="background:#343a40;border-radius:10px;color:white;width:100px;">

</form>
</div>
{% endif %}
{% if show_result == 'Yes' %}
<br>
<h1><b>Form Submitted Succesfully for the project manager to approve it.</b></h1>
<br>
<table class="table table-striped table-bordered"style="width:50%;">
  <tr>
    <th>Head</th>
    <th>Head Total</th>
  </tr>
  {% for i in li %}
  <tr>
    <td>{{ i.0 }}</td>
    <td>{{ i.1 }}</td>
  </tr>
  {% endfor %}
  <tr>
    <td>Grand Total</td>
    <td>{{ sum }}</td>
  </tr>
</table>
<br>
{% endif %}
{% endif %}
{% endblock %}

templates/transferMoney.html
{% extends 'template_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% block extra_head %}
<style>
label{
  font-size:20px;
}
#id_utranValue{
  width:300px;
}
#id_utranDesc{
  width:300px;
}
select{
  width:300px;
}
</style>
{% endblock %}
<h1 style="text-align:center;font-size:50px;border:1px solid black;"><b>Transfer Money</b></h1>
{% if user_access == 'No' %}
<h1>You cannot access this feature</h1>
{% else %}
{% if form %}
<form method="POST">
  <br>
  {% csrf_token %}
  {{ form|crispy }}
  <br>

  <button type="submit" style="background:#343a40;border-radius:10px;color:white;width:100px;">Submit</button>
</form>
{% endif %}
{% if success %}
<p>Hello</p>
{% endif %}
{% endif %}
{% endblock %}